### ISSUE TITLE
Buy method - "user conflict"

### ISSUE THREAD

**Issue by rumbaa01** [iaphub/react-native-iaphub#109]
Hello @iaphub  ,

I have the same issue as here described - https://github.com/iaphub/react-native-iaphub/issues/108

Let me describe the conditions first:

**Data:**
Platform - IOS
Apple Id account - the same 1 account
1st user account inside the app - A
2nd user account inside the app - B

**Steps:**
1. Buy a subscription to A account
2. Unsubscribe A account
3. Try to buy a subscription to B account

**Actual behavior:**
Code works as expected per your documentation. It will throw the next error - "user conflict".
<img width="836" alt="image" src="https://user-images.githubusercontent.com/15148689/161396316-aea24f1a-896c-4dd6-9575-3dc04cdc91bb.png">

**Expected behavior:**
1. Don't make the transaction
2. Get only error

**The main question is:**
Is it possible to not buy a product if the product belongs to a different user? Bc, it confuses me a lot as a user.

**Comment by iaphub** [comment]
Hi @rumbaa01,

We cannot know if the product belongs to another user before the user actually tries to purchase the product.
Please note this is a case that won't happen often and if it ever happen to a few users the error message will allow you to explain exactly why the purchase cannot be made.

PS: The user has the possibility to transfer the subscription from account A to account B by doing a restore. (Iaphub.restore() method).
