### ISSUE TITLE
Example > Android : !need extra step

### ISSUE THREAD

**Issue by cristea2017** [iaphub/react-native-iaphub#11]
step to reproduce : 

1. download example 
2. npm i
3. npx react-native run-android

ERROR > 

 What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/asd/Downloads/react-native-iaphub-master/Example/android/local.properties'.

Solution >
1.create new file  named local.properties in Android/ folder
2.add this `sdk.dir=/Users/asd/Library/Android/sdk` 
3. run again

**Comment by iaphub** [comment]
Thanks for the feedback @cristea2017, useful if any user has the same issue 👍
