### ISSUE TITLE
 Android  platform errror

### ISSUE THREAD

**Issue by WtfLaika** [iaphub/react-native-iaphub#110]
Hello @iaphub ,

I used before version iaphub 6.4.1 and decided to mirgrate to version 7.0.0. And after migration, when i'm trying to buy subscription on Android i get error.

![Screenshot_20220419_184452_com digilooms](https://user-images.githubusercontent.com/87127829/164043873-d04a70ef-ff3e-4f12-adfd-801859ba1532.jpg)

Conditions:

Data:
Platform - Android
Iaphub: 7.0.0
react-native: 0.64.1

Steps:
1. login to account with my uuid;
2. Get subscriptions;
3. Try to subscribe for product

Also had troubles  installing the last version. On site npmjs you have last version 6.4.2 https://www.npmjs.com/package/react-native-iaphub. I installed your library manually .

**Comment by WtfLaika** [comment]
Thank you!

**Comment by iaphub** [comment]
The issue has been fixed in the new version 7.0.1 👍
