### ISSUE TITLE
IOS subscription improvement

### ISSUE THREAD

**Issue by WtfLaika** [iaphub/react-native-iaphub#111]
@iaphub 
I saw a feature, that can resolve such a problem as separated subscription for each account. For example in Duolingo I can buy several subscriptions for several accounts.

![unnamed](https://user-images.githubusercontent.com/87127829/164245831-2dcbe7f2-9a1e-46e6-873a-f08989ccc025.jpeg)

So I tried to reproduce it with iaphub and it worked for android.

![1](https://user-images.githubusercontent.com/87127829/164250397-7dc6b50d-f2f1-4bb7-9941-38d65d5f6769.jpg)

Explanation of multiusers subscription:
1.Create a lot of clones of your subscriptions(for example 10 clones of monthly subscription).
2.Login in the first account and try to buy subscription.
3. Log out  and login to second account.
4. Try to buy that subscription, catch error "product_already_owned" and make loop forEach with massive of sku of your clones of that subscription each step of loop you try to buy clone of my subscription(if you didn't catch error "product_already_owned" stop loop)

Troubles:
1. (IOS) When you try to do the fourth step you either just replace subscription or can't buy clone of your subscription.
2. (Android and IOS)When i try to buy next clone of subscription i don't need error modal "you're already got this subscription".

Improvement:
1.(IOS) Give opportunity to buy more than one subscription for IOS.
2. Give opportunity to turn off error modal.

**Comment by iaphub** [comment]
Hi @WtfLaika,

Regarding your issues:
- If you replace the subscription it is because it is in the same subscription group (to be able to buy a different subscription, it needs to be in a different subscription group)
- We do not control the display of modals, it comes from iTunes.

**Comment by WtfLaika** [comment]
Thanks for your reply. Now I understand, how to implement multi
users subscriptions.
