### ISSUE TITLE
Bad business practices

### ISSUE THREAD

**Issue by ChristianMatthias** [iaphub/react-native-iaphub#112]
I used Iaphub to handle the subscriptions in my customers app. This worked kinda good. Unfortunately, this app failed but now I cannot cancel my subscription without paying more. Why do I need to pay to cancel my subscription?
I am now spammed with emails stating my subscription will be automatically canceled if my card declines, but when will this finally happen? 
The card will not work anymore because the customer whom I created the app for got bankrupt.

**Comment by iaphub** [comment]
Hey @ChristianMatthias,
As you can surely tell our billing system is automatic, if you have any issue you should simply contact our support (support@iaphub.com) and we would be happy to help.
