### ISSUE TITLE
 Iaphub.buy return a developer_error

### ISSUE THREAD

**Issue by talhajamshed-avomd** [iaphub/react-native-iaphub#116]
`      var transaction = await Iaphub.buy(productSku, {
        onReceiptProcess: () => console.log("-> Processing receipt"),
      });`
Error : developer_error [Error: Google is indicating that we have some issue connecting to payment.]

**Comment by iaphub** [comment]
Hi @talhajamshed-avomd,

Hard to say what's your issue, please contact the support (support@iaphub.com) and provide your app ID.
We'll try to check if we find any log that would explain such an error.
