### ISSUE TITLE
How to redeem code on both iOS and android

### ISSUE THREAD

**Issue by novellizator** [iaphub/react-native-iaphub#117]
So I found there is this 
**await Iaphub.presentCodeRedemptionSheet();** for iOS only. But what if I have a subscription for both ios and android and want to allow to redeem the code ?

**Comment by iaphub** [comment]
Hi @novellizator,

Android doesn't work like iOS, there is no method to open a promo code modal like iOS.
You can find the different options to enter a promo code on their documentation: https://developer.android.com/google/play/billing/promo#redeem
