### ISSUE TITLE
After update to 7.0.x, restore purchases isn't working

### ISSUE THREAD

**Issue by hdemmer** [iaphub/react-native-iaphub#118]
Hi! First, thanks for the new SDK version that has no legacy dependency.
A new issue started after the update:
When terminating the app just after a consumable purchase is made, that product remains in the "Already owned" state. The webhook is correctly delivered, but I cannot buy the consumable product again.
Restoring purchases either from the popup or by direct call does nothing. In the old version, that would flush out a stuck consumable purchase like this.
Platform is Android 11.
Are there any listeners or version upgrade steps I'm missing?

**Comment by iaphub** [comment]
Hi @hdemmer,
Thanks for the report, could you give me more details how to reproduce the issue? Are you terminating the app during the purchase? Thanks

**Comment by iaphub** [comment]
Fixed in v7.0.13 🙂
