### ISSUE TITLE
After update to 7.0.x, deferred purchases working

### ISSUE THREAD

**Issue by hdemmer** [iaphub/react-native-iaphub#119]
This is a separate issue from #118 but happened after the same SDK update:
Using the test card with delay on Google, I get the error code "unexpected" instead of "deferred_payment", both for the decline and accept with delay flows.
The accepted purchase eventually goes through and triggers the webhook, but the error code is wrong and thus I cannot present the "Please wait" feedback to the user.
Platform: Android 11

**Comment by iaphub** [comment]
We'll take a look at it, I'll let you know when we have a fix 👍

**Comment by iaphub** [comment]
Fixed in v7.0.13 🙂
