### ISSUE TITLE
Mac Catalyst Support?

### ISSUE THREAD

**Issue by scipilot** [iaphub/react-native-iaphub#122]
Would you be considering supporting Mac Catalyst soon?

We are assessing if we can publish a Mac desktop version of our app, so I have tried using Mac Catalyst support in the iOS workspace of my React Native app and found IAPHub is one of the Pods which doesn't seem to provide the necessary framework. 

e.g. when I compile (XCode 13.4.1 on MacOS 12.2.1) my React Native (v0.67.4) project I get these linker errors for IAPHub (v8) and also for an analytics package. All the other pods seems to compile OK, and I can run the app on the desktop if I remove these two.

```
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
      __swift_FORCE_LOAD_$_swiftUIKit_$_AnalyticsConnector in libAnalyticsConnector.a(AnalyticsConnector.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_AnalyticsConnector in libAnalyticsConnector.a(EventBridge.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_AnalyticsConnector in libAnalyticsConnector.a(IdentityStore.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_Iaphub in libIaphub.a(Iaphub.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_Iaphub in libIaphub.a(IHActiveProduct.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_Iaphub in libIaphub.a(IHProduct.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_Iaphub in libIaphub.a(IHReceipt.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_react_native_iaphub, __swift_FORCE_LOAD_$_swiftUIKit_$_Iaphub , __swift_FORCE_LOAD_$_swiftUIKit_$_amplitude_react_native , __swift_FORCE_LOAD_$_swiftUIKit_$_AnalyticsConnector )
ld: symbol(s) not found for architecture x86_64
```

I've started to look into what it takes to provide Mac OS / Catalyst support, but there's a lot to learn. e.g. I have read that Swift doesn't have a x86_64 runtime so can't be used in Catalyst, which I was pretty surprised to hear, and I'm not sure if that's still true.

thanks for any feedback

**Comment by iaphub** [comment]
Sorry but we have no plan to support Mac Catalyst in the very near future.
But I'll add it on our list of requested features.

**Comment by scipilot** [comment]
OK Thanks for letting me know.
