### ISSUE TITLE
Which  react-native-iap version should be used?

### ISSUE THREAD

**Issue by pisacode** [iaphub/react-native-iaphub#131]
Hi I just update the  react-native-iaphub to 8.2.3 and project stopped working because of misalignment with react-native-iap version.

```
 "react-native-iap": "5.2.6",
  "react-native-iaphub": "^8.2.3",
```

I couldn't find any documentation to know which versions to install

Thanks

**Comment by iaphub** [comment]
Hi @pisacode,

Starting from the version 7, the library doesn't use the react-native-iap dependency anymore.
Please check the migration guides: [v6 to v7](https://github.com/iaphub/react-native-iaphub/blob/master/guides/migrate-v6-to-v7.md) and [v7 to v8](https://github.com/iaphub/react-native-iaphub/blob/master/guides/migrate-v7-to-v8.md).
