### ISSUE TITLE
onUserUpdate not triggered after subscription expired 

### ISSUE THREAD

**Issue by Cantinaband** [iaphub/react-native-iaphub#132]
The event listener `onUserUpdate` isn't triggered from the subscription expired event `subscription_expire`.

Is this normal behavior? 

"react-native-iaphub": "8.2.3",

**Comment by iaphub** [comment]
Hey @Cantinaband,

Did you try to switch the app from background/foreground after the subscription expired? The event may not be triggered "live" right when the webhook is triggered and the app is open but it will the next time the app goes to foreground (there is also 1 min cache on the client side).

**Comment by iaphub** [comment]
Closing the issue but can still comment if further clarifications needed. Thanks
