### ISSUE TITLE
Error Xcode build: Include non-modular header inside framework module

### ISSUE THREAD

**Issue by n10ty** [iaphub/react-native-iaphub#136]
Versions:
"react-native-iap": "^12.4.14",
"react-native-iaphub": "^8.4.0",

It was successfully build before update to versions 5.1.0 -> 8.*
Android builds correct
ios fails
Any suggestions how to fix this?
 
<img width="396" alt="Screenshot 2023-01-15 at 16 25 16" src="https://user-images.githubusercontent.com/2970001/212550272-d6c2069e-2652-457f-8f12-91556cd47503.png">

**Comment by iaphub** [comment]
What's your version of React Native? We're now supporting the latest versions of react native and I believe this error should happen when using the plugin with an old version of react native.

But you should be able to fix the compilation error if you're not planning to upgrade React Native, you should add the following line in your Podfile  (below use_react_native)

``
pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
``

**Comment by n10ty** [comment]
@iaphub 
So I've update react-native from 0.65 to 0.71
```
    "react-native": "^0.71.1",
```

I also added the line you mentioned:
```
target 'renta' do
  use_frameworks! :linkage => :static
  # warn_for_unused_master_specs_repo => false

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"

  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])
  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
end
```

In `react-native-iaphub` I set 'allow non-modular includes in framework modules` to `true` as I read suggestion somewhere

<img width="1166" alt="Screenshot 2023-01-20 at 23 08 14" src="https://user-images.githubusercontent.com/2970001/213814292-8261e194-9b22-44a7-9ac7-af3d6aa475fd.png">

I also had both headers in public 
<img width="1013" alt="Screenshot 2023-01-20 at 23 12 52" src="https://user-images.githubusercontent.com/2970001/213814595-37add9a0-94ab-47ce-a672-0379177ddc9d.png">

And even with all this I'm still getting this errors (I'm doing Xcode "Clean build folder" before build)

Please reopen this issue until I will solve it.

**Comment by iaphub** [comment]
Ok, since you've updated React native, you do not need to modify your Pod file.
Also, you shouldn't have to modify the build settings.
Can you try to reset everything back to the default (the pod file and the build settings)? And run `pod install` in the ios directory of your project.

PS: You can also uninstall the `react-native-iap` dependency it isn't needed anymore since the v7.0.0 of the library.
