### ISSUE TITLE
Need to cast error to be able to use error.code

### ISSUE THREAD

**Issue by bulby97** [iaphub/react-native-iaphub#14]
Now I need to cast error to be able to use it. It would be cool to have the Error typed.

```
    const err = error as Error & { code: string }
```

**Comment by iaphub** [comment]
Thanks for the feedback @bulby97 , is it an issue due to the TypeScript definitions?

**Comment by bulby97** [comment]
Yep ! I can help if needed

**Comment by iaphub** [comment]
That would be great! If you submit a PR to fix your issue in index.d.ts I would be happy to merge it.
@centrual committed a PR recently to add TypeScript support.
I'm personally not using TypeScript but I should take a look at it someday 🙂

**Comment by centrual** [comment]
@bulby97 Please check https://github.com/iaphub/react-native-iaphub/pull/18
