### ISSUE TITLE
[iOS] Sandbox Subscription Persists When Changing Sandbox User Account

### ISSUE THREAD

**Issue by lucastonon** [iaphub/react-native-iaphub#142]
Hi, I am testing a monthly subscription in sandbox, and it works the first time. 
But then I can delete the app, change apple id sandbox account, reinstall the app
and when calling getActiveProducts() I'll receive the active subscription from the first account.

This has been reported as an issue on multiple forums on the internet, mostly from the native in-app SDK.
Most of them talk about calling finishTransactions to clear the queue as it might have been stuck.

Here are a couple of reports:

https://stackoverflow.com/questions/17172105/sandbox-inapp-purchase-restoring-purchases-of-perviously-logged-in-apple-account

https://stackoverflow.com/questions/17172105/sandbox-inapp-purchase-restoring-purchases-of-perviously-logged-in-apple-account

(Mine doesn't keep prompting but the error seems related)
https://stackoverflow.com/questions/10049521/in-app-purchases-sandbox-testing-old-sandbox-users-keep-prompting

What are your thoughts? Is there a way around it without full resetting my device every time I want to test an account?

Thank you

**Comment by iaphub** [comment]
The questions have of @lucastonon have been answered by email.

**Comment by bumpingChris** [comment]
Why do you answer by email and not let everyone see the response?
