### ISSUE TITLE
[iOS] Promotional code and subscription not working in App store build for IOS

### ISSUE THREAD

**Issue by govindaBump** [iaphub/react-native-iaphub#143]
Hi guys,
Promotional code and subscription not working in App store build for IOS
 All works fine for the staging and sandbox environments. 

"react-native": "0.69.7"
"react-native-iaphub": "8.4.2"

**Comment by iaphub** [comment]
Can you give more details @govindaBump? If you mean you can't enter the promo code in the code redemption sheet (https://github.com/iaphub/react-native-iaphub#present-code-redemption-sheet-ios-only) it isn't related to the plugin.

**Comment by kodie** [comment]
@iaphub My promo codes are able to be entered from the app store, but in the redemption sheet I get this message:

![IMG_0245](https://github.com/iaphub/react-native-iaphub/assets/603949/7cf855b0-ec59-4fa9-b1d3-e40a8147fef4)

What seems odd to me is the "appName" and "Subscription Offer". Is there more configuration that needs to be done in the app to allow code to be entered into the redemption sheet?

**Comment by iaphub** [comment]
It looks like a bug with Apple (you can contact the Apple support if needed). This modal is handled directly by iOS, not IAPHUB. Make sure you're using the last version of iOS. Also make sure you're not testing in sandbox (by running the app directly on your phone in local, it won't work unfortunately).
