### ISSUE TITLE
getActiveProducts return empty array right after login

### ISSUE THREAD

**Issue by voslartomas** [iaphub/react-native-iaphub#145]
Hello,

when I login user and call getActiveProducts it returns empty array even though user has subscription. If I restart application it load them just right. What could be the problem?

```
Iaphub.login(result.data.currentUser.id).then(() => {
              Iaphub.getActiveProducts() -> empty
...
```

I am testing on real iOS device.

**Comment by iaphub** [comment]
It looks like an issue with your account. You can contact the support (support@iaphub.com).
