### ISSUE TITLE
iOS privacy manifest - question

### ISSUE THREAD

**Issue by wojcik92michal** [iaphub/react-native-iaphub#147]
Hello!

Do you need to provide the changes related to iOS Privacy Manifest? (https://developer.apple.com/support/third-party-SDK-requirements/)

After using the tools from https://github.com/Wooder/ios_17_required_reason_api_scanner, it turns out that it discovers the following:
```
Used symbols in binary ./Iaphub/libIaphub.a: NSUserDefaults
```

The version that I am using is 8.4.2.

**Comment by iaphub** [comment]
Hi @wojcik92michal,

We added the privacy manifest file in the latest version of our SDK.
The issue should be fixed if you update react-native-iaphub to the latest version (8.6.2).
