### ISSUE TITLE
Google play billing version 5 expire by Aug 31, 2024

### ISSUE THREAD

**Issue by acaraty** [iaphub/react-native-iaphub#148]
Hello,

If I'm not mistaken the latest version of the Android SDK behind the react-native library uses the version 5 of google billing, and google won't accept app update with this version starting from august 31.

So my question is do you have any plan on releasing a new version of the Android and React-native SDKs any time soon to address this issue ?

Thanks a lot,
Aurélien

**Comment by iaphub** [comment]
Hello,

Yes, we will soon publish an update of our Android SDK using the Google Play Billing v6 library. It has already been developed, and we're currently testing it before release.

When you publish an update of your app after August 31, you'll simply need to update react-native-iaphub. The update won't have any breaking changes.

We will add a comment on this issue when the update is available 👍

**Comment by iaphub** [comment]
The latest release (v8.7.0) uses the Google Play Billing v6 library.
