### ISSUE TITLE
productsForSale is empty

### ISSUE THREAD

**Issue by gautam-ndk** [iaphub/react-native-iaphub#15]
Hi Team,
Thanks for the great library and the product. I'm running into an issue and hope you can help.

I followed the instructions and created a product and also published the listing on IAP HUB. But, when I fetch the user profile (.getUser()), the productsForSale is coming as an empty array.

Can you please let me know what might be going wrong here?

Thanks!

**Comment by ggunti** [comment]
Same at me. How did you solve it?
