### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by AlexisReverte** [iaphub/react-native-iaphub#2]
Hi,

Thx for this wonderful plugin, it help a lot the inapp purchase headache.

Is there a plan for having TypeScript definitions in the future, would be helpful :smile: 

Regards
Alexis

**Comment by iaphub** [comment]
Hi Alexis,

Thank you so much  🙏
I'm personally not using TypeScript but sure that's a thing we're gonna look at if it makes your life easier.
If you want to submit a PR I'll merge it.

Thanks

**Comment by centrual** [comment]
Hello guys,

I was made a typescript declaration for the project. Check this out: https://github.com/iaphub/react-native-iaphub/pull/9

Have a wonderful day!

**Comment by iaphub** [comment]
Awesome @centrual 👍 

I'll merge it right now, thank you for your contribution!
