### ISSUE TITLE
Why the userId must not be public?

### ISSUE THREAD

**Issue by SrBrahma** [iaphub/react-native-iaphub#26]
My userIds are provided by Firebase auth via Google/Apple/Facebook and are somewhat discoverable. What could go wrong if I used it in `await Iaphub.setUserId(...)`? I am going to use webhooks (will call Google Cloud Functions) to write on the DB that the user has made the purchase / refunded

**Comment by iaphub** [comment]
Nothing serious but for instance someone could know if a particular user id has an active subscription.

**Comment by SrBrahma** [comment]
Thanks. Not a real issue for my case.

Em qua, 23 de set de 2020 21:55, iaphub <notifications@github.com> escreveu:
