### ISSUE TITLE
Iaphub.restore() are coming as undefined

### ISSUE THREAD

**Issue by reberthkss** [iaphub/react-native-iaphub#28]
![image](https://user-images.githubusercontent.com/54030471/94494031-929e5580-01c4-11eb-9067-aa11d098a0cd.png)
![image](https://user-images.githubusercontent.com/54030471/94494075-a21d9e80-01c4-11eb-99a0-a93bc3143689.png)

**Comment by iaphub** [comment]
Hi @reberthkss,

It is normal, the restore method doesn't return any transaction.

**Comment by reberthkss** [comment]
@iaphub so can i just use Iaphub.getActiveSubscriptions() to handle previous transactions?

**Comment by iaphub** [comment]
Yes you could use `getActiveSubscriptions ` if you need to check if a subscription has been restored.
I'm closing the issue but feel free to reply if you're still having an issue.
