### ISSUE TITLE
About Google Play local pricing and more

### ISSUE THREAD

**Issue by SrBrahma** [iaphub/react-native-iaphub#29]
The Google Play console supports special IAP prices depending the user Country.

However, the IAPHUB console has just one price field. How is used this price field? Just for the statistics?

As Apple don't allow special prices depending of the location, I had the idea of naming my SKUs with "license_us_3m_1", being us the country code (any, maybe using 'zz' for fallback), 3m the subscription period, and 1 the version of the product. The frontend would then get its location (already managed to do that with Cloud Functions 'x-appengine-country' request header), and always select the highest product version, and the corresponding country code, or the fallback one.

Do you have any experience with special prices for countries? Have any better idea?

**Comment by iaphub** [comment]
Hey @SrBrahma,

IAPHUB is able to get the price/currency of the user, the price field is only used as the default pricing if for some reason we do not receive the products pricing of the user.
You should normally be able to setup different pricings depending on the country for subscriptions on Itunes/GooglePlay.
For consumable you're right it isn't possible on Itunes , you'll only be able to pick a tier.
But you easily enable the "Smart listing" feature on IAPHUB (Listings page) to return different products depending on the user country (Create a new store and add a filter by country).

Hope it helps.

**Comment by SrBrahma** [comment]
Thanks. Just to be sure: so, the price set in IAPHUB is just  a fallback for statistics, right? And maybe webhooks price field?

It won't change what appears to the buyer, neither my earnings, right?

You are being very helpful to me. Thanks! I hope this project of yours get very successful.

**Comment by iaphub** [comment]
Correct, it is just a fallback. Thank you @SrBrahma 🙏
