### ISSUE TITLE
Is there an API endpoint to create products on the fly?

### ISSUE THREAD

**Issue by kenma9123** [iaphub/react-native-iaphub#30]
Is there a way to create products to the dashboard other than manually doing it? We provide white label apps to clients and these clients have their own dashboard for setting up products on their end.

We could ask them to create the product on their own google play console and apple connect thats not a problem. But it would be nice if they could just fill out a form with their product SKU on our end then we can submit it to IAPHUB via API endpoint for faster transactions.

Is this process currently available or we have no way for automating the product creation?

**Comment by iaphub** [comment]
Hi @kenma9123, you wouldn't have to handle just products but product groups and listings as well.
Contact us at support@iaphub.com and give us a little bit more explanation about how your system exactly works and how many apps does it concern.
The easiest would be probably to give them access to their IAPHUB account.

Thanks
