### ISSUE TITLE
Manually trigger a webhook?

### ISSUE THREAD

**Issue by kenma9123** [iaphub/react-native-iaphub#33]
We have 2 different teams working on a iap feature. One for the mobile that handles the iap and the backend that will manage the webhook events. Is there a way to make test purchase, refund, etc and trigger the webhook smanually for specific type of events? or is this only achievable by completely setting up the prerequisite process for the mobile app?

**Comment by iaphub** [comment]
Hi @kenma9123,

No there isn't any way to 'trigger' a webhook manually.
You can find information about the webhooks on the documentation, it may help to understand how to handle them before testing on your app:
https://iaphub.com/docs/webhooks/purchase
