### ISSUE TITLE
Missing pod install instructions in documation

### ISSUE THREAD

**Issue by runebakjacobsen** [iaphub/react-native-iaphub#34]
Hey, thanks for your work! 

I am currently working on integrating it into my app. However I found that after I installed it with npm using your instructions, and trying to run it on ios, it gave me an error 

`error Could not find the following native modules: RNIap. Did you forget to run "pod install" ?`

I think it could benefit putting it in your install instructions that this is a provided step.

**Comment by iaphub** [comment]
Hi @runebakjacobsen,
Try to run "pod install" like it is advised in the error message (in the ios folder).
Let me know if it works 🙂

**Comment by runebakjacobsen** [comment]
> Hi @runebakjacobsen,
> Did it work after running "pod install" ?
> You're right this is something we could add in the README.

Yeah thanks I already did that. My issue was more a suggestion that your documentation maybe should include that in the installation step.

**Comment by iaphub** [comment]
Just did, thanks for the suggestion 👍
