### ISSUE TITLE
getProductsForSale() not returning all products

### ISSUE THREAD

**Issue by rbruels** [iaphub/react-native-iaphub#36]
I've been killing myself on this one. 

I cannot get `getProductsForSale()` to return more than one product, even though I have **two** fully setup in the IAPHub Dashboard and on App Store Connect.

On App Store Connect, one product is already for sale and live on the store, the other is "Ready for Review" but the "Cleared for Sale" checkbox is checked. Both of them are non-consumable (not subscriptions).

`react-native-iap`: `4.6.3`
`react-native-iaphub`: `5.1.0`
- iOS 14.2 (testing on-device)
- iPhone XS

Here's the code I'm using (somewhat simplified/overstylized for clarity):

```javascript
    import IAPHub from 'react-native-iaphub';
    ...
    const deviceId = DeviceInfo.getUniqueId();
    IAPHub.init({
      appId: '[removed my appID]',
      apiKey: '[removed my apiKey]',
      environment: 'production',
    })
    .then(() => {
      IAPHub.setUserId(deviceId)
      .then(() => {
        IAPHub.getProductsForSale()
        .then((products) => {
          console.log(products);  // *** here's where I'm expecting two products to return, but only get one... or zero...
        })
        .catch(err => {
          console.log(err);
        });
      })
      .catch(err => {
        console.log(err);
      });
    })
    .catch(err => {
      console.log(err);
    });
```

My device is only returning ONE of the TWO in-app purchases from `getProductsForSale()`.

Strangely, the result seems to change if I change the userID. For a while, one user was returning `[]` from `getProductsForSale()`. I changed its userID and then it started returning one product. But not two.  

If it helps, the product being returned is the one currently for sale on the App Store.

No errors are returned.

Am I missing the correct way to get ALL products for sale?

**Comment by iaphub** [comment]
Hi @rbruels,

I believe it could be one of your product that isn't returned by Itunes for some reason (misconfiguration maybe?).
Do you have any error "Product sku not found" in the console?
Could you please contact us at `support@iaphub.com` and give us your appId so we can take a look?

Thank you

**Comment by iaphub** [comment]
Closing the issue, if you're still having the issue you can contact us at `support@iaphub.com`.
