### ISSUE TITLE
No visible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet' 

### ISSUE THREAD

**Issue by leotm** [iaphub/react-native-iaphub#39]
### Version of react-native-iap

5.2.0

### Version of react-native

0.61.5

XCode 11.5

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Build successful

### Actual behavior

Build failed, 2 warnings, 1 error

https://github.com/dooboolab/react-native-iap/issues/1204

### Tested environment (Emulator? Real Device?)

Sim, emu

### Steps to reproduce the behavior

```sh
yarn add -E react-native-iap@5.2.0
yarn add -E react-native-iaphub@6.0.0
pod install
```

XCode > Clean
XCode > Build (or via RN CLI)

**Comment by leotm** [comment]
Downgrading to `"react-native-iap": "5.1.3"` builds, sticking with it for now

<img width="1680" alt="Screenshot 2020-12-09 at 16 16 14" src="https://user-images.githubusercontent.com/1881059/101656087-382e3a80-3a3a-11eb-9c76-0d806dda64dc.png">

Possibly related to old XCode 11.5 version, not yet on 12.1

**Comment by karlmarxlopez** [comment]
@leotm Are you using XCode 12?

**Comment by iaphub** [comment]
You're right @karlmarxlopez this error happen when compiling on xcode < 12.
@leotm I'm going to downgrade the react-native-iap version to 5.1.3 since we're not using the feature added in 5.2.0 (if it can help some people currently using xcode < 12)

**Comment by iaphub** [comment]
Deployed in version 6.0.1
