### ISSUE TITLE
Webhook not triggered!

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#40]
Hi guys!

I setted up a webhook in firebase cloud-functions but when i trigger a purchase event then nothing happen. When i update the webhook endpoint on iaphub settings, the test trigger is successful and i get the test request. Should i call some other api call or do you have any idea?
Would be great to give some advice.

Thx, for helping me.

**Comment by iaphub** [comment]
Hi @dancixx,
Seems like the issue is your endpoint is returning a 302 http code (iaphub isn't following redirections).
We are now reporting a 3xx code as invalid, you should see that your webhooks are failing 🙂

**Comment by iaphub** [comment]
Closing the issue if there is anything else you can contact us at `support@iaphub.com`

**Comment by dancixx** [comment]
Hi,

I get 302 http error, but when i save the endpoint, the webhook works as expected. I dont understand, should some authorization, but in the docs stay just should be.

**Comment by iaphub** [comment]
We just added the 302 http error as invalid, if you save your endpoint again you should get an error.

**Comment by dancixx** [comment]
I tested many times my endpoint, and i get the request.body correctly, i get that is and "type = test". So I dont know why dont get any request. The save method trigger my webhook endpoint, but the other events do nothing.

**Comment by iaphub** [comment]
You're definitely having an issue on your server, your server shouldn't return a 302.

**Comment by dancixx** [comment]
Ok. I try to find the solution, but dont know why test trigger works, other not. :)
