### ISSUE TITLE
Skus not found on Android

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#41]
Hi, i try to get products from IapHub but on android got always error, that skus not found. I tried wit react-native-iap and its worked, on ios iaphub works as expected.
Is it development error, or Iaphub settings error, but i have green light at android setup block?
Do you have any idea what should i do?

Iinit state is undefined.

Thx
Daniel

**Comment by iaphub** [comment]
react-native-iap is returning the infos of your product skus? That's would be weird because react-native-iaphub is using react-native-iap.
99% of the time this error means your sandbox environment isn't configured properly:
https://iaphub.com/docs/set-up-android/configure-sandbox-testing

**Comment by dancixx** [comment]
Yes i got the products if i use RNIap.getSubscriptions([array of productIds]). 
But iaphub doesnt work. I tried in all mode. Iaphub env: “production” and the app is published on playstore.

**Comment by dancixx** [comment]
Problem solved, close the issue, thx for you amazing library 👍
