### ISSUE TITLE
Hello I am getting a purchase error in Release build mode.

### ISSUE THREAD

**Issue by darkegn** [iaphub/react-native-iaphub#42]
Hello I am getting a purchase error in Release build mode. That's why I ate rejection from Apple. but there is no problem in the debug.

----------- Error -------------
: "Purchase error",
"We were not able to process your purchase, please try again later or contact the support (info@e-doping.com)"
<img width="944" alt="Screen Shot 2020-12-15 at 01 44 47" src="https://user-images.githubusercontent.com/26700764/102144794-281dbd00-3e77-11eb-9b63-2f140d161830.png">

**Comment by dancixx** [comment]
Hi!

I sucked with issue a lot of. You should create a sandbox user in appstoreconnect under users and persmissions, and generate an iap with this user. Then write this to apple support and everything will be okay.

**Comment by darkegn** [comment]
Hello, I do not know English well, I use google translate. I apologize if I write something wrong.

 I found the problem while testing streaming mode on real device. When I ran the Iaphub.init componentDidMount function in App.js it resolved. I sent a new request to Apple. I'm waiting for them to come back

If they say the same thing again, I will do what they say, thank you.
react-native-version: 0.61.5

**Comment by darkegn** [comment]
> Hi!
> 
> I sucked with issue a lot of. You should create a sandbox user in appstoreconnect under users and persmissions, and generate an iap with this user. Then write this to apple support and everything will be okay.

I will do what they say, thank you.

**Comment by iaphub** [comment]
Hope your issue will be resolved @darkegn 👍
