### ISSUE TITLE
published_listing_not_found error

### ISSUE THREAD

**Issue by harrisrobin** [iaphub/react-native-iaphub#43]
Hello 👋 

Running into the error in the title.
 
1. I have run the init.
2. I set the user's id
3. I try to call getProductsForSale() and i get a 400 with published_listing_not_found. 

I couldn't find any mention of this in the documentation or on github. What does this error mean?

Thank you,

**Comment by iaphub** [comment]
Hi @harrisrobin  👋

You're receiving this error because you did not create (and publish) a listing.
A listing is necessary for IAPHUB to know what products you have for sale:
https://iaphub.com/docs/getting-started/create-listing
