### ISSUE TITLE
Questions about library

### ISSUE THREAD

**Issue by ingerable** [iaphub/react-native-iaphub#45]
I just had few questions about the library, I'm not sure about some things

- How does restore work ? We would like to avoid accounts and use deviceID. If the user has a new device how does the restore method work ? We have to set the old device ID as userId and call restore ?
- Does Iaphub.getActiveProducts() count as an active user api call ? Because we would like to avoid having each user counted as active user just because we are checking if the user has subscribed and has access to premium features.

Best regards

**Comment by iaphub** [comment]
Hi @ingerable,

If your user has a new deviceID and does a restore, when IAPHUB receive the receipt it'll detect the purchases belong to a different deviceID and it'll transfer the purchases to the new deviceID. (You don't have to set the old deviceID).
Regarding the getActiveProducts method, yes it will, the pricing is based on the usage of the API.

If you have any other question, please let me know 🙂
