### ISSUE TITLE
Subscription modification error!

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#48]
Hi guys! I get always purchase error when i want to change the subscription product. I got success from itunes, but ipahub library drop error with the case of error "Couldn't buy product for many other reasons (the user shouldn't be charged)", but i got the success product change from iaphub too, but doesnt change the subscription product. Maybe this is a sandbox issue, or something wrong?

Thx for help.

**Comment by iaphub** [comment]
Hi @dancixx, what's the error code of your error? (err.code property)

**Comment by dancixx** [comment]
This is funny, i dont get error. So i tried today, on android, it works fine, the product change on iaphub dashboard as it should. But if i chagne the product in the app, the last alert screen what i got always, on android and ios too. The product is changed on iaphub dashboard if i tried on android, but on ios i think will not change cause after one period is expired the subscription in sandbox, so there is nothing to change.
![image](https://user-images.githubusercontent.com/56868953/102834720-244ce600-43f5-11eb-94be-31367e2eb25e.png)

**Comment by iaphub** [comment]
So no more issue?
I'm not sure to understand your issue but I think you're referring to a subscription downgrade, the subscription is replaced on the next renewal date (https://iaphub.com/docs/getting-started/create-subscription-groups#configure-a-subscription-group-on-itunes)

**Comment by dancixx** [comment]
So my problem the next:

Android:
1. purchase a subscription in sandbox  - done
2. got the success from from google - done
3. got the success alert from iaphub too - done
4. got the right webhook too - done
5. change the subscription in sandbox - done
6. got the success from google - done
7. iaphub webhook 'subscription replace' trigger - done
8. iaphub alert in app 'Purchase error', but everything was done before

IOS
1. purchase a subscription in sandbox  - done
2. got the success from from apple - done
3. got the success alert from iaphub too - done
4. got the right webhook too - done
5. change the subscription in sandbox - done
6. got the success from apple - done
7. **iaphub webhook 'subscription product change' trigger**, but should 'subscription replace', i think and indeed doesnt change because the subscription expire after 5 mins, on google is more period for sandobx
8. iaphub alert in app 'Purchase error', but everything was done before, expect the step 7

I hope my issue is more clear.
Thx for help.

**Comment by iaphub** [comment]
Thanks for the details @dancixx, how is it possible that you're having the alert in number 3 and number 8?
You're probably having this issue because you're calling the buy method 2 times? Maybe you're having a ghost click issue.

Regarding number 7 it is normal, you're receiving a "subscription product change" on a downgrade, more infos here:  https://iaphub.com/docs/getting-started/create-subscription-groups/#configure-a-subscription-group-on-itunes

**Comment by dancixx** [comment]
The 3rd alert came from first purchase. Under 8 steps i try to purchase for a product then change this product to another. At 3rd step i get the succes alert for the first purchase. After i try to update this product, then in the console and on iaphub dashboard works everything as expected, but the last alert is a purchase error. If i use the example buy method in the description what you give us, then got the last error section where the comment is // Couldn't buy product for many other reasons (the user shouldn't be charged).

**Comment by iaphub** [comment]
Ok I see, can you give me the message of the `err` property (the one thrown by the buy method) and also the `err.code` property?

**Comment by dancixx** [comment]
I found the issue now. I think now is issue solved. Thx for help.
