### ISSUE TITLE
subscription does not work on iOS 13.5 "Error: The operation couldn't be completed. (SKErrorDomain error 0)"

### ISSUE THREAD

**Issue by abbasaleid** [iaphub/react-native-iaphub#49]
Hello everyone, I've set up a subscription group on apple connect and did the same in iaphub dashboard. I've also configured a sandbox testing account and created a storekit file for testing on an iOS emulator. It works fine on iOS 14.x simulators and i'm able to subscribe to the monthly plans that I have created. However, when trying to subscribe on iOS 13.5 simulator I get the following error: `Error: The operation couldn't be completed. (SKErrorDomain error 0)`. 

It's worth mentioning that everything works fine on Android and i'm able to subscribe and manage subscriptions. 

React native: 0.63.4
react-native-iap: 5.1.3
react-native-iaphub: 6.0.3

**Comment by iaphub** [comment]
Hi @abbasaleid,
If you use a real device with no storekit file everything should work fine (otherwise IAPHUB won't be able to decode the receipt) 👍
