### ISSUE TITLE
Question regarding payment

### ISSUE THREAD

**Issue by eraldoforgoli** [iaphub/react-native-iaphub#50]
Hi, 
i have a question regarding the scope of this library. Does this library support the ui that the user chooses with what card he will pay, or do i have to install another library to support this, for example: 
![image](https://user-images.githubusercontent.com/24622515/103406973-f6864080-4b5c-11eb-8392-535411d620b9.png)

Thanks.

**Comment by iaphub** [comment]
Hi @eraldoforgoli,
The library is for In-app purchases (https://developer.apple.com/in-app-purchase/).
The credit card that is charged and everything else is directly handled by Apple and Google (It is not a library fo Apple Pay and Google Pay).
