### ISSUE TITLE
Getting TypeError: IAPHub.init is not a function

### ISSUE THREAD

**Issue by devaar100** [iaphub/react-native-iaphub#51]
"react-native": "^0.63.2",
"react-native-iap": "5.1.3",
"react-native-iaphub": "^6.0.5",

Code
import * as IAPHub from 'react-native-iaphub'
import { useDispatch } from 'react-redux'

const init = async () => {
    await IAPHub.init({
        appId: "id",
        apiKey: "key",
        environment: "production"
    })
}

I'll be really thankful if someone can help me out with this

**Comment by iaphub** [comment]
Hi @devaar100,

I think your issue is that you should the IAPHUB library like that:
`import Iaphub from 'react-native-iaphub';`

**Comment by devaar100** [comment]
<img width="554" alt="Screenshot 2021-01-05 at 9 15 10 AM" src="https://user-images.githubusercontent.com/29582559/103604291-a4676580-4f36-11eb-9df9-2b3fd16f3aed.png">

I tried with your way which is also in the docs and I am getting this error
That's why I tried to use the other way
If there is any other info about my project or set up i'll be happy to share that but kindly help me out here
