### ISSUE TITLE
Questions regarding the pricing 

### ISSUE THREAD

**Issue by eraldoforgoli** [iaphub/react-native-iaphub#52]
Hi, 

I have some questions regarding what is called an active user. 
Does calling the Iaphub.init() method, make the user counted as active, or only when calling setUserId() ?

If not, do you have a list of methods that would count the user as active  ?

When is the first moment that the user is counted as active ?

**Comment by iaphub** [comment]
Hi @eraldoforgoli ,

No it won't be called as active when calling the init method.
The user will be counted as active when calling the getProductsForSale or getActiveProducts methods.
