### ISSUE TITLE
No active products returned

### ISSUE THREAD

**Issue by karlmarxlopez** [iaphub/react-native-iaphub#53]
### Version

`6.0.4`

### Current Behavior

Not returning the active products from the published listing.

### Expected Behavior

It should show the list of active products when I query them using `getActiveProducts` method.

### Other info

```
react-native v0.63.2
react-native-iap v5.2.0
```

**Comment by iaphub** [comment]
Hi @karlmarxlopez,
Please contact us at `support@iaphub.com` and provide us your app id in order to take a better look at your app.
