### ISSUE TITLE
Error (plan_limit_reached)

### ISSUE THREAD

**Issue by scaralfred** [iaphub/react-native-iaphub#54]
Today I'm getting this error, while fetching products with this function => Iaphub.getProductsForSale()
Error: "api request returned an error (plan_limit_reached)"

I can't get the products...

But I did not even pushed the IAP feature to production, and there are just 10 "test users", so the 500 active users limit was not reached.

**Comment by iaphub** [comment]
Hi @scaralfred, you'll have to update your plan to production to increase the user limit, also if you use the same user id in dev you shouldn't have any issue with the limit.
https://iaphub.com/docs/getting-started/set-up-app#plan

**Comment by scaralfred** [comment]
Thanks for the answer, yes you are right, I understand now.

One question. As per this note:
"An user is counted as active when calling the IAPHUB API, it'll be identified by the user id you provide."

I assume that even active users are counted as active even if they don't have any active products, right? 
Which makes me think that is strongly recommended to make sure there will we potential active users... Cause my app has a monthly user base of 30.000 users... but if they won't make any purchase I will just end up paying the IAPHUB montlhy fee with any return. 

Am I right?

**Comment by iaphub** [comment]
Our pricing is based on the usage you're making of the service (like many other SaaS) not on how much you make.
I doubt all your users would use the service, you do not even have to call the getActiveProducts method, you could just save the subscription status of the user on your database using the webhooks (also not all your users are going to check the products for sale).

But we do understand it can be difficult to estimate the pricing depending on the usage of the service, this is why we're working on some exciting improvements of the pricing that will be released soon in order to make things easier 🙂

**Comment by scaralfred** [comment]
Thanks for your answer. Unfortunately I was hoping to use this service without any database... 
My app has no login and I was just using the "DeviceUniqueId" in order to identify the user.
As you will understand for my case there not so much I can do, other than calling a IAP HUB method as soon as the app launches... And this makes the pricing model a bit inconvenient for my case because my entire user base will be considered active regardless their interest in IAP products.
I look forward for your pricing model adjustments :)

**Comment by scaralfred** [comment]
Hello iaphub team. I just noticed that the pricing model has changed and it's now based on "monthly revenue" without even counting active users.
Can you confirm this right? 
This is exactly what I was looking for... :)

**Comment by iaphub** [comment]
Hi @scaralfred, yes we just deployed our new pricing plan and it doesn't count the number of active users indeed.
Should be way easier for you, hope you'll like it 🙂 

To migrate an existing app to the new pricing plan please email us at `support@iaphub.com` with your app id.

**Comment by scaralfred** [comment]
You are great company. I will email soon my app id. Thank you!
