### ISSUE TITLE
Support for Amazon app store

### ISSUE THREAD

**Issue by eladgel** [iaphub/react-native-iaphub#58]
Is that coming any time soon?

**Comment by iaphub** [comment]
Half the work is done, the server side is implemented, we need to finish the client side and write the documentation.
Cannot really give any timeline but it'll definitely come, we didn't have many request about Amazon, good to hear there is some interest.
Do you already have an app published on the Amazon Store?

**Comment by eladgel** [comment]
Not yet, we want to take what we did with the Google play store and duplicate it there
