### ISSUE TITLE
Update types for `getActiveProducts` and export subscription states

### ISSUE THREAD

**Issue by andrico1234** [iaphub/react-native-iaphub#59]
Even though `getActiveProducts` takes options as arguments, as specified in the README, it looks like these options haven't been added to the typings.

Also it would be useful to have the subscription states: `active`, `grace_period`, `retry_period`, and `paused` exported for type safety reasons.

Massive thanks to you all for making this package, it's a life saver, and so easy to use!

**Comment by andrico1234** [comment]
P.S. if you want to add this to the repo i'll behappy to quickly whip up an MR

**Comment by iaphub** [comment]
Thanks @andrico1234 🙏 
You're totally right, I just committed a fix: https://github.com/iaphub/react-native-iaphub/commit/11efbc52a7e264761b190e2c9f40a905837e628c
Let me know if it seems correct to you, thanks.

**Comment by andrico1234** [comment]
They're perfect! 🙌

**Comment by iaphub** [comment]
Great 👍  The fix is available in react-native-iaphub@6.1.1
