### ISSUE TITLE
apikey header is not working for api endpoints

### ISSUE THREAD

**Issue by appjitsu** [iaphub/react-native-iaphub#60]
We are using the sandbox environment and the server key that is listed in the settings of the IAPHUB portal.

<img width="1347" alt="Screen Shot 2021-02-04 at 10 40 31 AM" src="https://user-images.githubusercontent.com/10903600/106925143-6bf1ad80-66d5-11eb-8fc6-4745834ef010.png">

**Comment by iaphub** [comment]
Hi @appjitsu,

Seems like your Authorization header is incorrect, it should be `ApiKey [KEY]` there is no `:`.
If it still doesn't work, contact the support at `support@iaphub.com`
