### ISSUE TITLE
access_forbidden

### ISSUE THREAD

**Issue by appjitsu** [iaphub/react-native-iaphub#61]
im using postman to hit this endpoint:
https://api.iaphub.com/v1/app/6005c49014a85c0ea55e58a1/purchases

how do i fix this?

**Comment by iaphub** [comment]
Hi @appjitsu

I believe we already answered this issue here: https://github.com/iaphub/react-native-iaphub/issues/60
Otherwise please contact the support at `support@iaphub.com` since your issue isn't related to the react-native plugin, thanks 🙂
