### ISSUE TITLE
getProductsForSale issues in IOS

### ISSUE THREAD

**Issue by eladgel** [iaphub/react-native-iaphub#62]
### 2. For some users, the array returns null!

![image](https://user-images.githubusercontent.com/412137/107167516-eccad680-696d-11eb-9266-4dcf30008a5f.png)

We have 3 items to purchase:

1. Annual subs' 
2. Monthly subs
3. Lifetime. 
 
Annual, for some members does not return in the call, leading to a crash

On a different scenario the result returned form the same call returns null upon the call

Please advise!

**Comment by iaphub** [comment]
Hi @eladgel, please contact us at `support@iaphub.com` with the id of your app and the some user ids having this issue in order for us to investigate.
