### ISSUE TITLE
Delayed consumable purchase notification

### ISSUE THREAD

**Issue by ggunti** [iaphub/react-native-iaphub#63]
Let's say I have a "consumable" product. In test mode (android), if I buy it with a "Slow test card, declines after a few minutes" or "Slow test card, approves after a few minutes" (please check the image), both of them returns `err.code` equal to `'deferred_payment'`. So, later, when the purchase is approved / declined, how can I get a notification about it in my app?

Now, talking about production mode, if user uses a "Slow card" to buy a "consumable" product, I will get `'deferred_payment'` as error code, but later, after the purchase is accepted / declined, how can I get a notification about it in the app? (let's say I do not use webhooks)

Thanks!

![Screenshot_2021-02-11-11-40-57-238_com android vending](https://user-images.githubusercontent.com/26307699/107665140-d4242e80-6c95-11eb-8a3d-01598d86dbad.jpg)

**Comment by iaphub** [comment]
Hi @ggunti,
The only way would be with webhooks. If you're selling consumables the way to go is to use webhooks, handling your consumables on the client isn't safe.
