### ISSUE TITLE
In-App Purchases in terms of new Google regulations

### ISSUE THREAD

**Issue by lulmichal** [iaphub/react-native-iaphub#65]
Good Afternoon everyone!

I've just started my journey with software development, so my question might be a little trivial. Our clients requested that we should adapt our application to new Google regulations that is "**Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer**". I've tried to find out if every IAP library is based on Google Play Billing Library and is this issue even concerns us but I didn't find such information. Therefore I would like to know if GPBL is universal, it's standard and every IAP library is based on it? If so, does React Native Plugin is up to date with current regulations? If not, I would like someone reassure me that if I use React Native Plugin from IAPHUB I don't need to be worried about these particular regulations.

Thank you in advance!
Have a good day.

**Comment by iaphub** [comment]
Hi @lulmichal,
You don't have to worry, react-native-iaphub using the Google Billing Library version 3.
