### ISSUE TITLE
catch "user_cancelled"

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#69]
Hi!

Is there any way to handle event on "user_cancelled" event? When i started a buy request the customer get a loader screen, but he wants to cancel the popped up bottom actionsheet the "user_cancelled" event needs more then 10 seconds. Can I handle this cancel button event with this libarary or should look for something in react-native-iap?

Thx for help.

**Comment by stevenpersia** [comment]
Hi @dancixx !
What did you do to solve your problem ? :smiley:

**Comment by dancixx** [comment]
Hi @stevenpersia!

I used the `errorListener` from `react-native-iap`. Maybe my implementation can be useful to you as well. :)

```
useEffect(() => {
        RNIap.purchaseErrorListener((event) => {
            console.log(event);
            if (event.code === 'E_USER_CANCELLED') {
                // some logic here;
            }
        });
    }, []);
```

**Comment by stevenpersia** [comment]
Thanks for your quick return. I'll check it if it helps me :+1:
