### ISSUE TITLE
License type of this library

### ISSUE THREAD

**Issue by flogy** [iaphub/react-native-iaphub#70]
Hi there,

First of all, thanks for this great library!

I have a question about the license type of this library (GNU General Public License v3.0), though. As I understand, **this license type enforces every app to be open sources as well**, as soon as it uses this library (see: https://softwareengineering.stackexchange.com/a/47048). Do I understand this correctly and is this intended?

Because I think it would not be the ideal license type for a library whose main purpose is to add in-app-purchases more easily into apps, which probably is mostly required by commercially interested developers who would like to keep their app's source code closed.

Would it be possible to move to another but similar open source license without a copyleft paragraph? E.g. the MIT license?

Thanks in advance for your help.

**Comment by iaphub** [comment]
Hi @flogy,

Thanks for the feedback, it is not really clear indeed and it is not something we actually want.
I just switched it to the MIT license, it'll make things easier indeed 🙂

**Comment by flogy** [comment]
Awesome, thank you 🙂
