### ISSUE TITLE
Family sharing

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#72]
Hi guys. Can I detect with iaphub if somebody in a family sharing?

**Comment by iaphub** [comment]
Hey @dancixx, yes we do support iOS family sharing, you can check the `isFamilyShare ` property 👍

**Comment by dancixx** [comment]
I think about when a user has family package and the other one just got a seat in the family, the member who doesnt pay anything actually, is there a way to identify?

**Comment by iaphub** [comment]
Like I said you can use the `isFamilyShare` property we're exposing to detect if it's a free family share purchase.
Also keep in mind that if you want to offer this feature, the family sharing must be enabled on itunes connect, it is not enabled by default.
