### ISSUE TITLE
App Gallery Support (Huawei's Store In App Purchase)

### ISSUE THREAD

**Issue by amrdraz** [iaphub/react-native-iaphub#73]
Huawei's banned the google play store and a large, around 20-25%, of our user base are Huawei users,

Huawei already created a react react native package and offer new subscribers 100% off for the first 2 years as an incentive to join the store (at the time of this post)
https://www.npmjs.com/package/@hmscore/react-native-hms-iap

Would you consider setting up a guide for integrating App Gallery to display in your dashboard?

**Comment by iaphub** [comment]
Hey @amrdraz,
We currently do not support the huawei in-app purchases.
But this is something we'll definitely look at, will probably start working on the implementation later this year.
