### ISSUE TITLE
contact information IAPHUB

### ISSUE THREAD

**Issue by Robert-van-Barlingen** [iaphub/react-native-iaphub#74]
I realise that this is not the appropriate way to ask this question, but I am at my wits' end. What is the e-mail address at which I can contact IAPHUB? I cannot find it anywhere on the website. There was one post about the new pricing model which seemingly had a contact link,  but even that was simply a span element styled to look like a link... Seriously, what is the e-mail adres of IAPHUB?

**Comment by iaphub** [comment]
You can contact us at `support@iaphub.com` or directly from the chat button at the bottom right of the page.
