### ISSUE TITLE
Account charged

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#75]
Hi guys!

I sent an email to the support days ago but didn't get any response. My account was charged, but I used only sandbox data, and furthermore, I can't change my billing settings, especially my credit card information. Can u help me in this case?

**Comment by iaphub** [comment]
Hi @dancixx,
I'm sorry but we did not receive your email, can you reach us at `support@iaphub.com` ?
Your account has probably been charged because you're on a production plan, we're gonna take a look at it after your reach the support.
