### ISSUE TITLE
[QUESTION] Webhooks, restore

### ISSUE THREAD

**Issue by nartydev** [iaphub/react-native-iaphub#8]
Hello, 
Thanks for this great plugin 

I have some questions: 
- if I have no server to send for the webhook I can use this plugin ? I would like to save my purchases later, but not yet possible?
- my app doesn't have a login, so i use the deviceID for the ID of user, if the user changes the phone, he will suddenly have the option of being able to restore his purchases, right?

Thanks,

**Comment by iaphub** [comment]
Hello @nartydev !

Of course you can use this plugin without a server.
If you want to migrate your purchases to your server later, we'll provide you an API call to fetch them.

Regarding your question when you have no login system, it is indeed possible to use the device id (We just updated the README to specify that).
And you're right, if the user change his phone, he'll have to restore its purchases.

**Comment by iaphub** [comment]
I'm closing the issue, if you have any other question do not hesitate.
