### ISSUE TITLE
Payment failing in Android 

### ISSUE THREAD

**Issue by eraldoforgoli** [iaphub/react-native-iaphub#82]
Hi, 

During the following two days, many payments have failed on the Google Play store.
Some of the messages that we are getting are: 

Google is indicating that we have some issue connecting to payment.{"code":"developer_error","line":460,"column":20369,"sourceURL":"index.android.bundle"}

E_SERVICE_ERROR Billing is unavailable. This may be a problem with your device, or the Play Store may be down.

The service is unreachable. This may be your internet connection, or the Play Store may be down.{"code":"billing_unavailable","line":460,"column":20369,"sourceURL":"index.android.bundle"}

Payment is Cancelled.{"code":"user_cancelled","line":460,"column":20369,"sourceURL":"index.android.bundle"}

Billing is unavailable. This may be a problem with your device, or the Play Store may be down.{"nativeStackAndroid":[],"userInfo":null,"message":"Billing is unavailable. This may be a problem with your device, or the Play Store may be down.","code":"E_SERVICE_ERROR","line":18,"column":1111,"sourceURL":"index.android.bundle"}

Is this a problem with Google itself (the services are down), and how can we resolve the issue?

**Comment by iaphub** [comment]
Hi @eraldoforgoli,

Those errors come from Google indeed (not related to IAPHUB), are you maybe having network issues?
I dont think there is anything we can do, if the problem persist you can contact us at `support@iaphub.com`.

**Comment by flogy** [comment]
Had the same issue and for me it was related to the payment profile in the Google Play Developer account which was closed for some reason (see account > setup > payment profile).
