### ISSUE TITLE
How can I test the purchase multiple times in development?

### ISSUE THREAD

**Issue by ramos-lucas** [iaphub/react-native-iaphub#87]
When I was just using `react-native-iap`, I was able to buy the same product multiple times (with a warning).

Now I'm using this package and get an error when purchasing again the same product. What's the best way to buy a product multiple times without having to change my username every time?

**Comment by iaphub** [comment]
Hi @ramos-lucas ,
What kind of product are you selling? (subscription, consumable, non-consumable...)

**Comment by ramos-lucas** [comment]
Non-consumable

**Comment by ramos-lucas** [comment]
Actually, I can't buy again on the same device even changing the user. Must be because of the registered Sandbox account, right?
Is there any way I could avoid this behavior?

**Comment by iaphub** [comment]
Hi @ramos-lucas,
A non-consumable in tied to the account for life and it's unfortunately a pain to test indeed...
You could indeed use a different sandbox account on the phone (and use a different user id).
Another possibility would be to use a consumable to test your implementation, you can buy a consumable multiple times which makes testing way easier. (if IAPHUB can process a receipt with a consumable, it'll also work with a non-consumable).

**Comment by pisacode** [comment]
How can we consume a product on Android? @iaphub
