### ISSUE TITLE
Iaphub.getProductsForSale() doesn't return subscriptions

### ISSUE THREAD

**Issue by armin23615** [iaphub/react-native-iaphub#88]
I have a few non-renewable subscriptions on Google play console: 
![image](https://user-images.githubusercontent.com/56969846/125437294-02635ca4-374c-45a9-89aa-381c4c376ca3.png)

And I have one In-app product:
![image](https://user-images.githubusercontent.com/56969846/125437399-7f8d028a-9af1-4522-b042-79edd7c76915.png)

And this is the response I get from getProductsForSale(): 
```
 [{"description": "Enter a new team ", 
  "id": "60ed63576b49861697f3a726",
  "price": "$8.31",
  "priceAmount": 8.31, 
  "priceCurrency": "USD", 
  "sku": "enter_new_team_", 
  "title": "Enter a new team  (com.dartsorakelfantasy (unreviewed))", "type": "consumable"}]
```

Also for every subscription I get: 
" GooglePlay did not return the product 'player_and_events_12_months_', the product has been filtered, if the sku is valid your GooglePlay account or sandbox environment is probably not configured properly (https://iaphub.com/docs/set-up-android/configure-sandbox-testing)"

How to get those subscriptions too? 
I'm not sure what isn't configured correctly because I'm getting that one product.

These are my Iaphub products.
![image](https://user-images.githubusercontent.com/56969846/125438809-d0627408-61db-4157-8dcf-163e043d7284.png)

**Comment by armin23615** [comment]
However if I change subscription type to auto-renewable, it is returned in products array.

**Comment by iaphub** [comment]
Hi @armin23615,

If you're looking to sell non-renewable subscriptions on Android, you must create an 'In-app product', subscriptions on the Google Play Store are auto-renewable.

This is the cause of your issue, you could also edit your product type on IAPHUB to 'renewable subscription' and it should work (but it's gonna be an auto renewable subscription).
