### ISSUE TITLE
Iaphub.getProductsForSale() returning different product object for different users

### ISSUE THREAD

**Issue by dime8** [iaphub/react-native-iaphub#89]
I am getting different structured objects for two different users:

user 1 (have normal product object structure): 

 
![IMG_0322](https://user-images.githubusercontent.com/52378786/125447549-022b82df-ac0f-447d-ab9b-39a94945e773.PNG)

user 2 (missing price and subscriptionDuration in product objects):

![IMG_5626](https://user-images.githubusercontent.com/52378786/125447680-33174a34-880b-4f28-bb0c-2046bddaf364.PNG)

**Comment by iaphub** [comment]
Hi @dime8,

What's the version of react-native-iap you're using? You must be sure you're using react-native-iap@5.1.1

**Comment by iaphub** [comment]
I'm closing the issue but you can still comment if it didn't fix your problem 👍
