### ISSUE TITLE
Update to useIAP

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#90]
Hi guys,

do you plan to upgrade this library to the new hook feature, what was integrated into react-native-iap?

**Comment by iaphub** [comment]
Hi @dancixx,
No, we do not have the need. Why do you need it?

**Comment by dancixx** [comment]
I just was curious because the hooks are the future in react.

**Comment by iaphub** [comment]
Alright got it, if we integrate hooks it would be independent from react-native-iap but this is definitely something we're going to think about implementing in a next release.
