### ISSUE TITLE
Subscription renewal retry

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#91]
Hi guys,

I need a bit of help. One of my subscribers stuck in `"subscriptionState":"retry_period"` state. This happened a month ago, but I didn't get any webhook about, that the system tried to charge him. I have to wait till 60 days or what should I do in this case? How can I recover the subscription fee?

**Comment by iaphub** [comment]
Hi @dancixx,
Please contact `support@iaphub.com` with your app id and the user id of the user, we'll take a look.
