### ISSUE TITLE
Free trial

### ISSUE THREAD

**Issue by dancixx** [iaphub/react-native-iaphub#94]
Hi guys,

I tried to add a free trial period to my iOS subscription plans but I couldn't find the right was. Is it possible that Apple allows only the introductory price for them? It is important because I should separate the products by iOS and Android because Google allows the trial period but on the IapHub dashboard I can check only the free trial or the introductory option.
My other question is that, if the user pays for a subscription with a trial option it will trigger the same `purchase` webhook event immediately or just at the end of the trial period?

Thanks for the help.

**Comment by iaphub** [comment]
Hi @dancixx, not sure to understand your issue, you can contact the support at `support@iaphub.com`.
Regarding the webhook, yes the purchase webhook is triggered for a free trial.
