### ISSUE TITLE
receipt_validation_failed IOS error

### ISSUE THREAD

**Issue by jeffersribeiro** [iaphub/react-native-iaphub#97]
hello, good afternoon I'm trying to finalize a purchase on iOS devices but I'm getting this error "receipt_validation_failed", could give me a suggestion of what it might be? on the IAPHUB painel i have this error "error_expiration_date_empty".

**Comment by AngelDev727** [comment]
Hollo,
I am going to purchase on iOS device.
But I am getting receipt is fail on the IAPHUB painel i have this error "error_expiration_date_empty".
How can I fix it?
